### ISSUE TITLE
Make Witchery / Thaumcraft more useful

### ISSUE THREAD

**Issue by ghost** [Ghalid/BIKES6#8]
In what ways could we do this?

As for Thaumcraft, we currently have Void metal ingots required to craft Infusion Stones from Magical Crops. What should we do for Witchery (and anything else for Thaumcraft)?

**Comment by jamzss** [comment]
**Witchery**

- Attuned Stones are relatively inexpensive gems, but require quite a bit of random chance and processing of specific saplings inside a Witches Oven

- Koboldite Ingots are rare ingots obtained by trading with Hobgoblins for both nuggets and dust (81 dust = 1 ingot), but the dust is only obtainable by a Hobgoblin when they go digging, so this could be used in recipes more towards endgame 

- Impregnated Leather has a reasonably involved crafting recipe, involving the Witches Oven and the Distillery

**Thaumcraft**

- Thaumium Ingots, if removed from all loot tables & loot bags, serve as a material slightly more valuable than iron, can be crafted relatively early on in normal Thaumcraft progression, and later have its production automated fully.

- Void Seeds can be crafted in late-game Thaumcraft, or dropped by Cultists and Crimson Knights with a 20% chance to drop 0-1 seeds, and Void Ingots are crafted in a Crucible using these seeds also with late-game and valuable essentias.

- Nitor is a very inexpensive crafting material, made by using simple aspects, or throwing  torches, 2 coal and 1 glowstone dust into a crucible.

**Comment by ghost** [comment]
Several useful items from tech mods now require items from Witchery or Thaumcraft. If anyone feels that they should be used in more recipes, please reopen this issue.
